In [2]:
import os
import numpy as np
# from __future__ import division
from matplotlib import pyplot
import pandas as pd
from pandas.plotting import autocorrelation_plot
from pandas.plotting import autocorrelation_plot

In [36]:
#  Yearly Resultaten
Resultats= pd.read_csv("outM4all.csv", skiprows=0, index_col =0)
Resultats
columnsname= ["model","sMape Yearly","Mase Yearly"]
ds_yearly = pd.DataFrame(columns=columnsname )
#ds.to_csv('yearly_resultat.csv')
ds_yearly.iloc[:,0]= Resultats.iloc[:,0]
ds_yearly.iloc[:,1]= Resultats.iloc[:,6]
ds_yearly.iloc[:,2]= Resultats.iloc[:,13]
ds_yearly

                   model  sMape Yearly  Mase Yearly
0       LinearRegression        0.3260      79.3850
1  DecisionTreeRegressor        0.3297       5.2569
2    KNeighborsRegressor        0.3076       4.7270
3                    SVR        0.3983       5.3667
4              MLP_Bench        0.1976       3.2508
5              RNN_Bench        0.1939       3.2733

In [37]:
#  Quaterly Resultaten
Resultats= pd.read_csv("outM4all.csv", skiprows=0, index_col =0)
Resultats
columnsname= ["model","sMape Quaterly","Mase Quaterly"]
ds_quaterly = pd.DataFrame(columns=columnsname )
#ds.to_csv('yearly_resultat.csv')
ds_quaterly.iloc[:,0]= Resultats.iloc[:,0]
ds_quaterly.iloc[:,1]= Resultats.iloc[:,5]
ds_quaterly.iloc[:,2]= Resultats.iloc[:,12]
ds_quaterly

                   model  sMape Yearly  Mase Yearly
0       LinearRegression        0.1648       1.7004
1  DecisionTreeRegressor        0.1236       1.5097
2    KNeighborsRegressor        0.1334       1.6275
3                    SVR        0.2731       3.5039
4              MLP_Bench        0.1314       1.4956
5              RNN_Bench        0.1303       1.6035

In [34]:
Resulta= pd.read_csv("outM4all.csv", skiprows=0, index_col =0)
Resulta

,Model,sMape Hourly,sMape Daily,sMape Weekly,sMape Monthly,sMape Quaterly,sMape Yearly,sMAPE TOTAL,Mase Hourly,Mase Daily,Mase Weekly,Mase Monthly,Mase Quaterly,Mase Yearly,MAPE TOTAL,OWA
0,LinearRegression,0.3705,0.0274,0.0977,0.0820,0.1648,0.3260,0.1781,9.6697,3.4331,2.4266,0.9492,1.7004,79.3850,16.2607,8.2194
1,DecisionTreeRegressor,0.4435,0.0308,0.0787,0.1000,0.1236,0.3297,0.1844,8.9419,3.8206,2.2111,1.1702,1.5097,5.2569,3.8184,2.0014
2,KNeighborsRegressor,0.3634,0.0311,0.0901,0.1229,0.1334,0.3076,0.1747,6.6049,3.8947,2.3570,1.3455,1.6275,4.7270,3.4261,1.8004
3,SVR,0.5552,0.1403,0.2441,0.1195,0.2731,0.3983,0.2884,45.0352,13.7135,14.4623,1.4976,3.5039,5.3667,13.9299,7.1091
4,MLP_Bench,0.0000,0.0000,0.1934,0.1470,0.1314,0.1976,0.0000,0.0000,0.0000,7.0898,2.0041,1.4956,3.2508,0.0000,0.0000
5,RNN_Bench,0.0000,0.0000,0.1114,0.1340,0.1303,0.1939,0.0000,0.0000,0.0000,3.8246,1.2320,1.6035,3.2733,0.0000,0.0000

In [18]:
Resultats.iloc[:,13]

0    79.3850
1     5.2569
2     4.7270
3     5.3667
Name: Mase Yearly, dtype: float64

In [13]:
Resultats1= pd.read_csv("outputM4_20_sample.csv", skiprows=0, index_col =0)
Resultats1.T

                     0               1             2            3
Data_Type  Yearly_data  Quarterly_data  Monthly_data  Weekly_data
sMape MLP     0.197638        0.131421      0.146993     0.193492
sMape RNN     0.193903        0.130282      0.133996     0.111373
Mase MLP       3.25085         1.49558       2.00413       7.0898
Mase RNN       3.27333         1.60348       1.23198      3.82459